# this goes to the file that assembles the image
W: 480
H: 600
iw: 440
ih: 440
lw: 50
lh: 50
logo_buffer: 100
default_logo: 'https://github.com/klunn91/team-logos/blob/master/NCAA/_NCAA_logo.png?raw=true'
