# this is stuff for posting to shop
base_url : "https://api.printify.com/v1"
shop_id : 13647323
title: 'test'
price: 2000
description: 'this a test'
tags: 'this,a,test'
blueprint_id: 6
print_provider_id: 87
variant_ids:
  - 12070
  - 12071
  - 12072
  - 12073
  - 12074
  # - 12075
  - 12100
  - 12101
  - 12102
  - 12103
  - 12104
  # - 12105
shop_name: '70f8b8-5'