name: run

on:
  schedule:
    - cron: '1 0 * * *' # every morn
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: set secrets
        shell: bash
        run: echo ${{ secrets.private }} | base64 --decode > info/private.yml

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python test.py

        